export const PH_CITY_REGION_OPTIONS = [
  { city: "Laoag", region: "Region I – Ilocos Region" },
  { city: "Batac", region: "Region I – Ilocos Region" },
  { city: "Vigan", region: "Region I – Ilocos Region" },
  { city: "Candon", region: "Region I – Ilocos Region" },
  { city: "City of San Fernando", region: "Region I – Ilocos Region" },
  { city: "Dagupan", region: "Region I – Ilocos Region" },
  { city: "Alaminos", region: "Region I – Ilocos Region" },
  { city: "Urdaneta", region: "Region I – Ilocos Region" },
  { city: "San Carlos", region: "Region I – Ilocos Region" },
  { city: "Tuguegarao", region: "Region II – Cagayan Valley" },
  { city: "Ilagan", region: "Region II – Cagayan Valley" },
  { city: "Cauayan", region: "Region II – Cagayan Valley" },
  { city: "Santiago", region: "Region II – Cagayan Valley" },
  { city: "Balanga", region: "Region III – Central Luzon" },
  { city: "Malolos", region: "Region III – Central Luzon" },
  { city: "Meycauayan", region: "Region III – Central Luzon" },
  { city: "San Jose del Monte", region: "Region III – Central Luzon" },
  { city: "Baliwag", region: "Region III – Central Luzon" },
  { city: "Cabanatuan", region: "Region III – Central Luzon" },
  { city: "Gapan", region: "Region III – Central Luzon" },
  { city: "Palayan", region: "Region III – Central Luzon" },
  { city: "San Jose", region: "Region III – Central Luzon" },
  { city: "Muñoz", region: "Region III – Central Luzon" },
  { city: "San Fernando", region: "Region III – Central Luzon" },
  { city: "Angeles", region: "Region III – Central Luzon" },
  { city: "Mabalacat", region: "Region III – Central Luzon" },
  { city: "Tarlac City", region: "Region III – Central Luzon" },
  { city: "Olongapo", region: "Region III – Central Luzon" },
  { city: "Batangas City", region: "Region IV-A – CALABARZON" },
  { city: "Lipa", region: "Region IV-A – CALABARZON" },
  { city: "Tanauan", region: "Region IV-A – CALABARZON" },
  { city: "Sto. Tomas", region: "Region IV-A – CALABARZON" },
  { city: "Calaca", region: "Region IV-A – CALABARZON" },
  { city: "Bacoor", region: "Region IV-A – CALABARZON" },
  { city: "Carmona", region: "Region IV-A – CALABARZON" },
  { city: "Cavite City", region: "Region IV-A – CALABARZON" },
  { city: "Dasmariñas", region: "Region IV-A – CALABARZON" },
  { city: "General Trias", region: "Region IV-A – CALABARZON" },
  { city: "Imus", region: "Region IV-A – CALABARZON" },
  { city: "Tagaytay", region: "Region IV-A – CALABARZON" },
  { city: "Trece Martires", region: "Region IV-A – CALABARZON" },
  { city: "Biñan", region: "Region IV-A – CALABARZON" },
  { city: "Cabuyao", region: "Region IV-A – CALABARZON" },
  { city: "Calamba", region: "Region IV-A – CALABARZON" },
  { city: "San Pablo", region: "Region IV-A – CALABARZON" },
  { city: "San Pedro", region: "Region IV-A – CALABARZON" },
  { city: "Santa Rosa", region: "Region IV-A – CALABARZON" },
  { city: "Lucena", region: "Region IV-A – CALABARZON" },
  { city: "Tayabas", region: "Region IV-A – CALABARZON" },
  { city: "Antipolo", region: "Region IV-A – CALABARZON" },
  { city: "Calapan", region: "MIMAROPA Region" },
  { city: "Puerto Princesa", region: "MIMAROPA Region" },
  { city: "Legazpi", region: "Region V – Bicol Region" },
  { city: "Ligao", region: "Region V – Bicol Region" },
  { city: "Tabaco", region: "Region V – Bicol Region" },
  { city: "Naga City", region: "Region V – Bicol Region" },
  { city: "Iriga", region: "Region V – Bicol Region" },
  { city: "Masbate City", region: "Region V – Bicol Region" },
  { city: "Sorsogon City", region: "Region V – Bicol Region" },
  { city: "Roxas", region: "Region VI – Western Visayas" },
  { city: "Iloilo City", region: "Region VI – Western Visayas" },
  { city: "Passi", region: "Region VI – Western Visayas" },
  { city: "Tagbilaran", region: "Region VII – Central Visayas" },
  { city: "Cebu City", region: "Region VII – Central Visayas" },
  { city: "Mandaue", region: "Region VII – Central Visayas" },
  { city: "Lapu-Lapu", region: "Region VII – Central Visayas" },
  { city: "Bogo", region: "Region VII – Central Visayas" },
  { city: "Carcar", region: "Region VII – Central Visayas" },
  { city: "Danao", region: "Region VII – Central Visayas" },
  { city: "City of Naga", region: "Region VII – Central Visayas" },
  { city: "Talisay", region: "Region VII – Central Visayas" },
  { city: "Toledo", region: "Region VII – Central Visayas" },
  { city: "Borongan", region: "Region VIII – Eastern Visayas" },
  { city: "Tacloban", region: "Region VIII – Eastern Visayas" },
  { city: "Ormoc", region: "Region VIII – Eastern Visayas" },
  { city: "Baybay", region: "Region VIII – Eastern Visayas" },
  { city: "Calbayog", region: "Region VIII – Eastern Visayas" },
  { city: "Catbalogan", region: "Region VIII – Eastern Visayas" },
  { city: "Maasin", region: "Region VIII – Eastern Visayas" },
  { city: "Dipolog", region: "Region IX – Zamboanga Peninsula" },
  { city: "Dapitan", region: "Region IX – Zamboanga Peninsula" },
  { city: "Pagadian", region: "Region IX – Zamboanga Peninsula" },
  { city: "Zamboanga City", region: "Region IX – Zamboanga Peninsula" },
  { city: "Malaybalay", region: "Region X – Northern Mindanao" },
  { city: "Valencia", region: "Region X – Northern Mindanao" },
  { city: "Iligan", region: "Region X – Northern Mindanao" },
  { city: "Ozamiz", region: "Region X – Northern Mindanao" },
  { city: "Oroquieta", region: "Region X – Northern Mindanao" },
  { city: "Tangub", region: "Region X – Northern Mindanao" },
  { city: "Gingoog", region: "Region X – Northern Mindanao" },
  { city: "El Salvador", region: "Region X – Northern Mindanao" },
  { city: "Tagum", region: "Region XI – Davao Region" },
  { city: "Panabo", region: "Region XI – Davao Region" },
  { city: "Samal", region: "Region XI – Davao Region" },
  { city: "Digos", region: "Region XI – Davao Region" },
  { city: "Davao City", region: "Region XI – Davao Region" },
  { city: "Mati", region: "Region XI – Davao Region" },
  { city: "Kidapawan", region: "Region XII – SOCCSKSARGEN" },
  { city: "Koronadal", region: "Region XII – SOCCSKSARGEN" },
  { city: "General Santos", region: "Region XII – SOCCSKSARGEN" },
  { city: "Tacurong", region: "Region XII – SOCCSKSARGEN" },
  { city: "Cabadbaran", region: "Region XIII – Caraga" },
  { city: "Butuan", region: "Region XIII – Caraga" },
  { city: "Bayugan", region: "Region XIII – Caraga" },
  { city: "Surigao City", region: "Region XIII – Caraga" },
  { city: "Bislig", region: "Region XIII – Caraga" },
  { city: "Tandag", region: "Region XIII – Caraga" },
  { city: "Caloocan", region: "NCR – National Capital Region" },
  { city: "Las Piñas", region: "NCR – National Capital Region" },
  { city: "Makati", region: "NCR – National Capital Region" },
  { city: "Malabon", region: "NCR – National Capital Region" },
  { city: "Mandaluyong", region: "NCR – National Capital Region" },
  { city: "City of Manila", region: "NCR – National Capital Region" },
  { city: "Marikina", region: "NCR – National Capital Region" },
  { city: "Muntinlupa", region: "NCR – National Capital Region" },
  { city: "Navotas", region: "NCR – National Capital Region" },
  { city: "Parañaque", region: "NCR – National Capital Region" },
  { city: "Pasay", region: "NCR – National Capital Region" },
  { city: "Pasig", region: "NCR – National Capital Region" },
  { city: "Quezon City", region: "NCR – National Capital Region" },
  { city: "San Juan", region: "NCR – National Capital Region" },
  { city: "Taguig", region: "NCR – National Capital Region" },
  { city: "Valenzuela", region: "NCR – National Capital Region" },
  { city: "Baguio", region: "CAR – Cordillera Administrative Region" },
  { city: "Tabuk", region: "CAR – Cordillera Administrative Region" },
  { city: "Lamitan", region: "BARMM – Bangsamoro Autonomous Region in Muslim Mindanao" },
  { city: "City of Isabela", region: "BARMM – Bangsamoro Autonomous Region in Muslim Mindanao" },
  { city: "Marawi", region: "BARMM – Bangsamoro Autonomous Region in Muslim Mindanao" },
  { city: "Cotabato City", region: "BARMM – Bangsamoro Autonomous Region in Muslim Mindanao" },
  { city: "Bacolod", region: "NIR – Negros Island Region" },
  { city: "Bago", region: "NIR – Negros Island Region" },
  { city: "Cadiz", region: "NIR – Negros Island Region" },
  { city: "Escalante", region: "NIR – Negros Island Region" },
  { city: "Himamaylan", region: "NIR – Negros Island Region" },
  { city: "Kabankalan", region: "NIR – Negros Island Region" },
  { city: "La Carlota", region: "NIR – Negros Island Region" },
  { city: "Sagay", region: "NIR – Negros Island Region" },
  { city: "City of San Carlos", region: "NIR – Negros Island Region" },
  { city: "Silay", region: "NIR – Negros Island Region" },
  { city: "Sipalay", region: "NIR – Negros Island Region" },
  { city: "Victorias", region: "NIR – Negros Island Region" },
  { city: "Dumaguete", region: "NIR – Negros Island Region" },
  { city: "Bais", region: "NIR – Negros Island Region" },
  { city: "Bayawan", region: "NIR – Negros Island Region" },
  { city: "Canlaon", region: "NIR – Negros Island Region" },
  { city: "Guihulngan", region: "NIR – Negros Island Region" },
  { city: "Tanjay", region: "NIR – Negros Island Region" },
];

export const CITY_TO_REGION = Object.fromEntries(PH_CITY_REGION_OPTIONS.map((x) => [x.city, x.region]));
